apiVersion: v1alpha1
kind: Setting
metadata:
  name: meilisearch-settings
spec:
  forms:
    - group: base
      label: 基本设置
      formSchema:
        - $formkit: text
          label: host
          name: host
          validation: required
          value: 'http://meilisearch:7700'
        - $formkit: text
          label: masterKey
          name: masterKey
          validation: required
          value: '95d031f029c0f93289791d39f01a7f42a2211973'
        - $formkit: text
          label: 搜索结果长度
          name: cropLength
          validation: required|Number
          value: '80'